version: '2'
services:
  app:
    image: app_imapi
    working_dir: /var/www
    volumes:
      - ./:/var/www
  web:
    image: web_imapi
    working_dir: /var/www
    volumes_from:
      - app
    ports:
      - 9000:80
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: imapi
      MYSQL_USER: imapi
      MYSQL_PASSWORD: imapi
      MYSQL_ROOT_PASSWORD: root
    command: --default-authentication-plugin=mysql_native_password --bind-address=0.0.0.0
    ports:
      - "127.0.0.1:3306:3306"
    volumes:
      - db_data:/var/lib/mysql
  rabbitmq:
    image: rabbitmq:3-management
    hostname: "dev-rabbitmq"
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - /home/phooto/rabbit:/var/lib/rabbitmq/mnesia
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 5s
      timeout: 5s
      retries: 5
volumes:
  db_data:
