#!/bin/sh
 
cd /var/www

# chmod -R 777 storage/
# rm -r vendor 
# rm -r composer.lock
# composer dump-autoload
# composer install --no-scripts 
# composer require lcobucci/jwt:3.3.1
# php artisan config:clear
# php artisan cache:clear

#supervisord
#supervisorctl start all

set -e

# first arg is `-f` or `--some-option`
if [ "${1#-}" != "$1" ]; then
	set -- php-fpm "$@"
fi

exec "$@"